### ISSUE TITLE
Posibility to remove keys

### ISSUE THREAD

**Issue by qarmin** [eugene-bulkin/rust-bk-tree#13]
I wanted to remove item from tree, but I couldn't find any method how to do this(opposite to `add`)

**Comment by MikeCain** [comment]
Hi @qarmin!
The short answer is, removing from a BK Tree is non-trivial in general.
Here's a related StackOverflow question: https://stackoverflow.com/questions/42230648/deleting-a-node-in-a-bk-tree

Depending on your use case and how many elements you're looking to delete, you could consider keeping a "deleted" data structure and ignoring results after-the-fact, or reconstructing a new BK tree.
