### ISSUE TITLE
Should BKTree be renamed to BkTree instead?

### ISSUE THREAD

**Issue by lambda-fairy** [eugene-bulkin/rust-bk-tree#5]
Rust code tends to capitalize only the first letter of abbreviations. For example, the [`IpAddr`][1] and [`Rc`][2] types are written this way. For consistency, I think we should name this structure `BkTree` as well.

[1]: https://doc.rust-lang.org/std/net/enum.IpAddr.html
[2]: https://doc.rust-lang.org/std/rc/struct.Rc.html

**Comment by eugene-bulkin** [comment]
Only reason I'm not immediately for this is that BK stands for two names (Burkhard-Keller), rather than two non-proper nouns (Internet Protocol, Reference Counted). So I don't know if it would actually make sense in this case.

**Comment by lambda-fairy** [comment]
While doing some unrelated work, I came across [this comment](https://stackoverflow.com/questions/4504508/camel-casing-acronyms#comment4930698_4504521):

> An additional guideline is: if the acronym is derived from the names of people, then keep all of it upper cased. It's "RSACryptoServiceProvider", not "RsaCryptoServiceProvider". Would you want to be the one to tell Shamir or Adelman that they don't rate a capital letter? I think not. :-)

So I'll take Eric Lippert's word on this :)
