### ISSUE TITLE
Link to Documentation broken

### ISSUE THREAD

**Issue by MikeCain** [eugene-bulkin/rust-bk-tree#6]
The link to the documentation, [https://eugene-bulkin.github.io/rust-docs/rust-bk-tree/bk_tree/](https://eugene-bulkin.github.io/rust-docs/rust-bk-tree/bk_tree/), results in a 404 error.

**Comment by eugene-bulkin** [comment]
Fixed with ebf31ab. I just directed the link to the auto-generated docs.rs one.
