### ISSUE TITLE
SIMD-accelerated Levenshtein and Hamming distance

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [eugene-bulkin/rust-bk-tree#7]
Hello, I was looking at BK-tree implementations and I saw your library. I am working on speeding up Levenshtein distance calculations with SIMD in my library [here](https://crates.io/crates/triple_accel/), and I was wondering whether you would be interested in incorporating the Hamming and Levenshtein distance metrics to the library in addition to the current Levenshtein metric. I think this would be an interesting addition for faster searches on long ASCII strings. I am willing to work on an implementation and pull request.

**Comment by eugene-bulkin** [comment]
Closed (as far as I can tell) via #9.
